package com.tina.app.data

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import androidx.sqlite.execSQL
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO

@Database(
    entities = [Item::class, ChatEntity::class, ChatMessageEntity::class, OccurrenceCompletion::class],
    version = 5,
)
@TypeConverters(Converters::class)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun itemDao(): ItemDao
    abstract fun chatDao(): ChatDao
    abstract fun occurrenceDao(): OccurrenceDao
}

/** Additive: ask-chat tables only. Items are untouched — this must never be destructive. */
private val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL(
            "CREATE TABLE IF NOT EXISTS `chats` (" +
                "`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`title` TEXT NOT NULL, `model` TEXT, `reasoning` TEXT NOT NULL, " +
                "`createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL)",
        )
        connection.execSQL(
            "CREATE TABLE IF NOT EXISTS `chat_messages` (" +
                "`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`chatId` INTEGER NOT NULL, `role` TEXT NOT NULL, " +
                "`content` TEXT NOT NULL, `createdAt` INTEGER NOT NULL)",
        )
        connection.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_chat_messages_chatId` ON `chat_messages` (`chatId`)",
        )
    }
}

// Actuals are generated by the Room compiler per platform.
@Suppress("NO_ACTUAL_FOR_EXPECT", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/** Additive: adds the soft-delete column. Existing items keep NULL and stay visible. */
private val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL("ALTER TABLE `items` ADD COLUMN `deletedAt` INTEGER")
    }
}

/** Additive: per-occurrence completion for repeating items. Items are untouched. */
private val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL(
            "CREATE TABLE IF NOT EXISTS `occurrence_completions` (" +
                "`itemId` INTEGER NOT NULL, `epochDay` INTEGER NOT NULL, " +
                "`skipped` INTEGER NOT NULL, `completedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`itemId`, `epochDay`))",
        )
    }
}

fun buildDatabase(builder: RoomDatabase.Builder<AppDatabase>): AppDatabase =
    builder
        .setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        .addMigrations(MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5)
        // v1 was the pre-feature scaffold with an empty placeholder table; nothing worth migrating
        .fallbackToDestructiveMigration(dropAllTables = true)
        .build()
